# Example: show battery status, charge, graph, and remaining time.

set -g @plugin 'gufranco/tmux-battery-revamped'

set -g @battery_revamped_status_discharging_fg_color '#[fg=yellow]'
set -g @battery_revamped_status_charging_fg_color '#[fg=green]'

set -g status-right '#{battery_color_status_fg}#{battery_icon_status} #{battery_percentage}#[default] #{battery_graph} #{battery_remain} '
